import type { AutoPostPlatform, Plan, Reciter, VideoTemplate } from "./types";

export const surahs: {
  number: number;
  name: string;
  arabic: string;
  ayahs: number;
}[] = [
  { number: 1, name: "Al-Fatihah", arabic: "الفاتحة", ayahs: 7 },
  { number: 2, name: "Al-Baqarah", arabic: "البقرة", ayahs: 286 },
  { number: 3, name: "Ali Imran", arabic: "آل عمران", ayahs: 200 },
  { number: 4, name: "An-Nisa", arabic: "النساء", ayahs: 176 },
  { number: 5, name: "Al-Ma'idah", arabic: "المائدة", ayahs: 120 },
  { number: 6, name: "Al-An'am", arabic: "الأنعام", ayahs: 165 },
  { number: 7, name: "Al-A'raf", arabic: "الأعراف", ayahs: 206 },
  { number: 8, name: "Al-Anfal", arabic: "الأنفال", ayahs: 75 },
  { number: 9, name: "At-Tawbah", arabic: "التوبة", ayahs: 129 },
  { number: 10, name: "Yunus", arabic: "يونس", ayahs: 109 },
  { number: 11, name: "Hud", arabic: "هود", ayahs: 123 },
  { number: 12, name: "Yusuf", arabic: "يوسف", ayahs: 111 },
  { number: 13, name: "Ar-Ra'd", arabic: "الرعد", ayahs: 43 },
  { number: 14, name: "Ibrahim", arabic: "إبراهيم", ayahs: 52 },
  { number: 15, name: "Al-Hijr", arabic: "الحجر", ayahs: 99 },
  { number: 16, name: "An-Nahl", arabic: "النحل", ayahs: 128 },
  { number: 17, name: "Al-Isra", arabic: "الإسراء", ayahs: 111 },
  { number: 18, name: "Al-Kahf", arabic: "الكهف", ayahs: 110 },
  { number: 19, name: "Maryam", arabic: "مريم", ayahs: 98 },
  { number: 20, name: "Ta-Ha", arabic: "طه", ayahs: 135 },
  { number: 21, name: "Al-Anbiya", arabic: "الأنبياء", ayahs: 112 },
  { number: 22, name: "Al-Hajj", arabic: "الحج", ayahs: 78 },
  { number: 23, name: "Al-Mu'minun", arabic: "المؤمنون", ayahs: 118 },
  { number: 24, name: "An-Nur", arabic: "النور", ayahs: 64 },
  { number: 25, name: "Al-Furqan", arabic: "الفرقان", ayahs: 77 },
  { number: 26, name: "Ash-Shu'ara", arabic: "الشعراء", ayahs: 227 },
  { number: 27, name: "An-Naml", arabic: "النمل", ayahs: 93 },
  { number: 28, name: "Al-Qasas", arabic: "القصص", ayahs: 88 },
  { number: 29, name: "Al-Ankabut", arabic: "العنكبوت", ayahs: 69 },
  { number: 30, name: "Ar-Rum", arabic: "الروم", ayahs: 60 },
  { number: 31, name: "Luqman", arabic: "لقمان", ayahs: 34 },
  { number: 32, name: "As-Sajdah", arabic: "السجدة", ayahs: 30 },
  { number: 33, name: "Al-Ahzab", arabic: "الأحزاب", ayahs: 73 },
  { number: 34, name: "Saba", arabic: "سبأ", ayahs: 54 },
  { number: 35, name: "Fatir", arabic: "فاطر", ayahs: 45 },
  { number: 36, name: "Ya-Sin", arabic: "يس", ayahs: 83 },
  { number: 37, name: "As-Saffat", arabic: "الصافات", ayahs: 182 },
  { number: 38, name: "Sad", arabic: "ص", ayahs: 88 },
  { number: 39, name: "Az-Zumar", arabic: "الزمر", ayahs: 75 },
  { number: 40, name: "Ghafir", arabic: "غافر", ayahs: 85 },
  { number: 41, name: "Fussilat", arabic: "فصلت", ayahs: 54 },
  { number: 42, name: "Ash-Shura", arabic: "الشورى", ayahs: 53 },
  { number: 43, name: "Az-Zukhruf", arabic: "الزخرف", ayahs: 89 },
  { number: 44, name: "Ad-Dukhan", arabic: "الدخان", ayahs: 59 },
  { number: 45, name: "Al-Jathiyah", arabic: "الجاثية", ayahs: 37 },
  { number: 46, name: "Al-Ahqaf", arabic: "الأحقاف", ayahs: 35 },
  { number: 47, name: "Muhammad", arabic: "محمد", ayahs: 38 },
  { number: 48, name: "Al-Fath", arabic: "الفتح", ayahs: 29 },
  { number: 49, name: "Al-Hujurat", arabic: "الحجرات", ayahs: 18 },
  { number: 50, name: "Qaf", arabic: "ق", ayahs: 45 },
  { number: 51, name: "Adh-Dhariyat", arabic: "الذاريات", ayahs: 60 },
  { number: 52, name: "At-Tur", arabic: "الطور", ayahs: 49 },
  { number: 53, name: "An-Najm", arabic: "النجم", ayahs: 62 },
  { number: 54, name: "Al-Qamar", arabic: "القمر", ayahs: 55 },
  { number: 55, name: "Ar-Rahman", arabic: "الرحمن", ayahs: 78 },
  { number: 56, name: "Al-Waqi'ah", arabic: "الواقعة", ayahs: 96 },
  { number: 57, name: "Al-Hadid", arabic: "الحديد", ayahs: 29 },
  { number: 58, name: "Al-Mujadila", arabic: "المجادلة", ayahs: 22 },
  { number: 59, name: "Al-Hashr", arabic: "الحشر", ayahs: 24 },
  { number: 60, name: "Al-Mumtahanah", arabic: "الممتحنة", ayahs: 13 },
  { number: 61, name: "As-Saff", arabic: "الصف", ayahs: 14 },
  { number: 62, name: "Al-Jumu'ah", arabic: "الجمعة", ayahs: 11 },
  { number: 63, name: "Al-Munafiqun", arabic: "المنافقون", ayahs: 11 },
  { number: 64, name: "At-Taghabun", arabic: "التغابن", ayahs: 18 },
  { number: 65, name: "At-Talaq", arabic: "الطلاق", ayahs: 12 },
  { number: 66, name: "At-Tahrim", arabic: "التحريم", ayahs: 12 },
  { number: 67, name: "Al-Mulk", arabic: "الملك", ayahs: 30 },
  { number: 68, name: "Al-Qalam", arabic: "القلم", ayahs: 52 },
  { number: 69, name: "Al-Haqqah", arabic: "الحاقة", ayahs: 52 },
  { number: 70, name: "Al-Ma'arij", arabic: "المعارج", ayahs: 44 },
  { number: 71, name: "Nuh", arabic: "نوح", ayahs: 28 },
  { number: 72, name: "Al-Jinn", arabic: "الجن", ayahs: 28 },
  { number: 73, name: "Al-Muzzammil", arabic: "المزمل", ayahs: 20 },
  { number: 74, name: "Al-Muddaththir", arabic: "المدثر", ayahs: 56 },
  { number: 75, name: "Al-Qiyamah", arabic: "القيامة", ayahs: 40 },
  { number: 76, name: "Al-Insan", arabic: "الإنسان", ayahs: 31 },
  { number: 77, name: "Al-Mursalat", arabic: "المرسلات", ayahs: 50 },
  { number: 78, name: "An-Naba", arabic: "النبأ", ayahs: 40 },
  { number: 79, name: "An-Nazi'at", arabic: "النازعات", ayahs: 46 },
  { number: 80, name: "Abasa", arabic: "عبس", ayahs: 42 },
  { number: 81, name: "At-Takwir", arabic: "التكوير", ayahs: 29 },
  { number: 82, name: "Al-Infitar", arabic: "الانفطار", ayahs: 19 },
  { number: 83, name: "Al-Mutaffifin", arabic: "المطففين", ayahs: 36 },
  { number: 84, name: "Al-Inshiqaq", arabic: "الانشقاق", ayahs: 25 },
  { number: 85, name: "Al-Buruj", arabic: "البروج", ayahs: 22 },
  { number: 86, name: "At-Tariq", arabic: "الطارق", ayahs: 17 },
  { number: 87, name: "Al-A'la", arabic: "الأعلى", ayahs: 19 },
  { number: 88, name: "Al-Ghashiyah", arabic: "الغاشية", ayahs: 26 },
  { number: 89, name: "Al-Fajr", arabic: "الفجر", ayahs: 30 },
  { number: 90, name: "Al-Balad", arabic: "البلد", ayahs: 20 },
  { number: 91, name: "Ash-Shams", arabic: "الشمس", ayahs: 15 },
  { number: 92, name: "Al-Layl", arabic: "الليل", ayahs: 21 },
  { number: 93, name: "Ad-Duhaa", arabic: "الضحى", ayahs: 11 },
  { number: 94, name: "Ash-Sharh", arabic: "الشرح", ayahs: 8 },
  { number: 95, name: "At-Tin", arabic: "التين", ayahs: 8 },
  { number: 96, name: "Al-Alaq", arabic: "العلق", ayahs: 19 },
  { number: 97, name: "Al-Qadr", arabic: "القدر", ayahs: 5 },
  { number: 98, name: "Al-Bayyinah", arabic: "البينة", ayahs: 8 },
  { number: 99, name: "Az-Zalzalah", arabic: "الزلزلة", ayahs: 8 },
  { number: 100, name: "Al-Adiyat", arabic: "العاديات", ayahs: 11 },
  { number: 101, name: "Al-Qari'ah", arabic: "القارعة", ayahs: 11 },
  { number: 102, name: "At-Takathur", arabic: "التكاثر", ayahs: 8 },
  { number: 103, name: "Al-Asr", arabic: "العصر", ayahs: 3 },
  { number: 104, name: "Al-Humazah", arabic: "الهمزة", ayahs: 9 },
  { number: 105, name: "Al-Fil", arabic: "الفيل", ayahs: 5 },
  { number: 106, name: "Quraysh", arabic: "قريش", ayahs: 4 },
  { number: 107, name: "Al-Ma'un", arabic: "الماعون", ayahs: 7 },
  { number: 108, name: "Al-Kawthar", arabic: "الكوثر", ayahs: 3 },
  { number: 109, name: "Al-Kafirun", arabic: "الكافرون", ayahs: 6 },
  { number: 110, name: "An-Nasr", arabic: "النصر", ayahs: 3 },
  { number: 111, name: "Al-Masad", arabic: "المسد", ayahs: 5 },
  { number: 112, name: "Al-Ikhlas", arabic: "الإخلاص", ayahs: 4 },
  { number: 113, name: "Al-Falaq", arabic: "الفلق", ayahs: 5 },
  { number: 114, name: "An-Nas", arabic: "الناس", ayahs: 6 },
];

// Reciter ids must exactly match the backend's accepted `reciterId` enum
export const reciters: Reciter[] = [
  {
    id: "ar.alafasy",
    name: "Mishary Alafasy",
    arabicName: "مشاري العفاسي",
    style: "Modern · Melodic",
  },
  {
    id: "ar.abdurrahmaansudais",
    name: "Abdur-Rahman As-Sudais",
    arabicName: "عبد الرحمن السديس",
    style: "Soulful · Nasheed",
  },
  {
    id: "ar.mahermuaiqly",
    name: "Maher Al Muaiqly",
    arabicName: "ماهر المعيقلي",
    style: "Traditional",
  },
  {
    id: "ar.abdulbasitmurattal",
    name: "Abdul Basit (Murattal)",
    arabicName: "عبد الباسط",
    style: "Classic · Murattal",
  },
  {
    id: "ar.abdulsamad",
    name: "Abdul Basit Abdus-Samad",
    arabicName: "عبدالباسط عبدالصمد",
    style: "Classic",
  },
  {
    id: "ar.husary",
    name: "Mahmoud Al-Husary",
    arabicName: "محمود الحصري",
    style: "Tartil · Slow",
  },
  {
    id: "ar.minshawi",
    name: "Muhammad Al-Minshawi",
    arabicName: "محمد صديق المنشاوي",
    style: "Classic",
  },
  {
    id: "ar.ahmedajamy",
    name: "Ahmed Al-Ajamy",
    arabicName: "أحمد العجمي",
    style: "Modern",
  },
  {
    id: "ar.shaatree",
    name: "Abu Bakr Ash-Shaatree",
    arabicName: "أبو بكر الشاطري",
    style: "Melodic",
  },
  {
    id: "ar.saoodshuraym",
    name: "Saud Al-Shuraim",
    arabicName: "سعود الشريم",
    style: "Traditional",
  },
  {
    id: "ar.hudhaify",
    name: "Ali Al-Hudhaify",
    arabicName: "علي الحذيفي",
    style: "Tartil",
  },
  {
    id: "ar.muhammadayyoub",
    name: "Muhammad Ayyoub",
    arabicName: "محمد أيوب",
    style: "Melodic",
  },
  {
    id: "ar.muhammadjibreel",
    name: "Muhammad Jibreel",
    arabicName: "محمد جبريل",
    style: "Traditional",
  },
  {
    id: "ar.abdullahbasfar",
    name: "Abdullah Basfar",
    arabicName: "عبد الله بصفر",
    style: "Classic",
  },
  {
    id: "ar.husarymujawwad",
    name: "Al-Husary (Mujawwad)",
    arabicName: "محمود خليل الحصري (المجود)",
    style: "Mujawwad",
  },
  {
    id: "ar.minshawimujawwad",
    name: "Al-Minshawi (Mujawwad)",
    arabicName: "محمد صديق المنشاوي (المجود)",
    style: "Mujawwad",
  },
  {
    id: "ar.hanirifai",
    name: "Hani Ar-Rifai",
    arabicName: "هاني الرفاعي",
    style: "Modern",
  },
  {
    id: "ar.aymanswoaid",
    name: "Ayman Sowaid",
    arabicName: "أيمن سويد",
    style: "Tartil",
  },
  {
    id: "ar.dosari",
    name: "Yasser Al-Dosari",
    arabicName: "ياسر الدوسري",
    style: "Soulful",
  },
];

export const templates: VideoTemplate[] = [
  {
    id: "emerald-glow",
    name: "Emerald Glow",
    motion: "Subtle Zoom",
    gradient: "from-emerald-deep to-emerald-mint",
    pattern: "arabesque",
  },
  {
    id: "golden-dusk",
    name: "Golden Dusk",
    motion: "Pan & Fade",
    gradient: "from-gold to-gold-light",
    pattern: "calligraphic",
  },
  {
    id: "night-sky",
    name: "Night Sky",
    motion: "Particle Drift",
    gradient: "from-slate-800 to-indigo-900",
    pattern: "geometric",
  },
  {
    id: "desert-min",
    name: "Desert Minimal",
    motion: "Static Text",
    gradient: "from-amber-700 to-amber-900",
    pattern: "minimal",
  },
  {
    id: "ocean-calm",
    name: "Ocean Calm",
    motion: "Wave Pulse",
    gradient: "from-cyan-800 to-teal-900",
    pattern: "geometric",
  },
  {
    id: "royal-green",
    name: "Royal Green",
    motion: "Slow Zoom",
    gradient: "from-green-700 to-emerald-deep",
    pattern: "arabesque",
  },
];

/** Catalog of platforms supported for social connect / auto-post (connection state comes from the real user record). */
export const integrationPlatforms: {
  key: AutoPostPlatform;
  platform: string;
}[] = [
  { key: "youtube", platform: "YouTube Shorts" },
  { key: "tiktok", platform: "TikTok" },
  { key: "facebook", platform: "Facebook Pages" },
];

/** Plan tier limits per the backend spec — used for gating UI and upsell messaging. */
export const planTierLimits: Record<
  Plan,
  {
    maxClipSeconds: number;
    manualRendersPerMonth: number;
    autoPostsPerMonth: number;
    watermark: boolean;
  }
> = {
  FREE: {
    maxClipSeconds: 10,
    manualRendersPerMonth: 3,
    autoPostsPerMonth: 0,
    watermark: true,
  },
  PRO: {
    maxClipSeconds: 60,
    manualRendersPerMonth: 15,
    autoPostsPerMonth: 5,
    watermark: false,
  },
  ULTIMATE: {
    maxClipSeconds: 120,
    manualRendersPerMonth: -1,
    autoPostsPerMonth: 30,
    watermark: false,
  },
};

export const pricingPlans = [
  {
    id: "FREE" as const,
    name: "Free",
    priceNGN: 0,
    tagline: "Get started with AI verse videos",
    features: [
      "3 renders per month",
      "Up to 10s video duration",
      "Watermark on videos",
      "19 reciter voices",
      "Manual downloads",
    ],
    limits: { renders: 3, duration: 10, watermark: true },
    highlight: false,
  },
  {
    id: "PRO" as const,
    name: "Pro",
    priceNGN: 5000,
    tagline: "For creators & small da'wah channels",
    features: [
      "15 renders per month",
      "Up to 60s video duration",
      "No watermark",
      "All reciter voices",
      "Auto-Post up to 5 times/month",
      "Priority queue",
    ],
    limits: { renders: 15, duration: 60, watermark: false },
    highlight: true,
  },
  {
    id: "ULTIMATE" as const,
    name: "Ultimate",
    priceNGN: 12000,
    tagline: "Scale your da'wah content engine",
    features: [
      "Unlimited renders",
      "Up to 120s video duration",
      "No watermark",
      "All reciter voices",
      "Auto-Post up to 30 times/month (~daily)",
      "Priority queue + custom branding",
    ],
    limits: { renders: -1, duration: 120, watermark: false },
    highlight: false,
  },
];

export const durationOptions = [1, 3, 6, 12];
